ShopMVC/Controllers/InquiryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ShopMVC_DataAccess;
using ShopMVC_Models;
using ShopMVC_Utility;
using ShopMVC_ViewModels;

namespace ShopMVC.Controllers
{
    [Authorize(Roles = WebConstants.AdminRole)]
    public class InquiryController : Controller
    {
        [BindProperty]
        public InquiryViewModel InquiryViewModel { get; set; }
        private readonly IInquiryHeaderRepository inquiryHeaderDB;
        private readonly IInquiryDetailsRepository inquiryDetailsDB;

        public InquiryController(IInquiryHeaderRepository inquiryHeaderDB,
            IInquiryDetailsRepository inquiryDetailsDB)
        {
            this.inquiryHeaderDB = inquiryHeaderDB;
            this.inquiryDetailsDB = inquiryDetailsDB;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Details(int? id)
        {
            var inquiryHeader = inquiryHeaderDB.FindById(id.GetValueOrDefault());

            if (inquiryHeader == null)
                return NotFound();

            var includeProperties = new List<string>() { WebConstants.ProductName };
            var inquiryDetailsList = inquiryDetailsDB.GetAll(predicate: x => x.InquiryHeaderId == id,
                includeProperties: includeProperties).ToList();

            InquiryViewModel = new InquiryViewModel()
            {
                InquiryHeader = inquiryHeader,
                InquiryDetailsList = inquiryDetailsList
            };

            return View(InquiryViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Details(InquiryViewModel model)
        {
            InquiryViewModel.InquiryDetailsList = inquiryDetailsDB.GetAll(predicate: x => x.InquiryHeaderId == model.InquiryHeader.Id,
                includeProperties: new List<string>() { WebConstants.ProductName }).ToList();

            var shoppingCartList = new List<ShoppingCart>();

            shoppingCartList = InquiryViewModel.InquiryDetailsList.Select(x => new ShoppingCart()
            {
                ProductId = x.ProductId,
                Sqft = x.Product.TempSqft
            }).ToList();

            HttpContext.Session.Clear();
            HttpContext.Session.Set(WebConstants.SessionCart, shoppingCartList);
            HttpContext.Session.Set(WebConstants.SessionInquiryId, model.InquiryHeader.Id);

            return RedirectToAction("Index", "ShoppingCart");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(InquiryViewModel model)
        {
            var inquiryHeader = inquiryHeaderDB.FindById(model.InquiryHeader.Id);

            if (inquiryHeader == null)
                return NotFound();

            var inquiryDetails = inquiryDetailsDB.GetAll(predicate: x => x.InquiryHeaderId == inquiryHeader.Id)
                                                  .ToList();

            inquiryHeaderDB.Remove(inquiryHeader);
            inquiryDetails.ForEach(x => inquiryDetailsDB.Remove(x));
            inquiryDetailsDB.Save();

            return RedirectToAction(nameof(Index));
        }

        #region API CALLS

        [HttpGet]
        public IActionResult GetInquiryList()
        {
            return Json(new { data = inquiryHeaderDB.GetAll() });
        }

        #endregion
    }
}

ShopMVC/Controllers/OrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using ShopMVC_DataAccess;
using ShopMVC_Models;
using ShopMVC_Utility;

namespace ShopMVC.Controllers
{
    [Authorize(Roles = WebConstants.AdminRole)]
    public class OrderController : Controller
    {
        private readonly IOrderHeaderRepository orderHeaderDB;
        private readonly IOrderDetailsRepository orderDetailsDB;
        private readonly IBrainTreeGate brain;

        public OrderController(IOrderHeaderRepository orderHeaderDB,
            IOrderDetailsRepository orderDetailsDB,
            IBrainTreeGate brain)
        {
            this.orderHeaderDB = orderHeaderDB;
            this.orderDetailsDB = orderDetailsDB;
            this.brain = brain;
        }

        [HttpGet]
        public IActionResult Index(string searchName = null, 
            string searchEmail = null,
            string searchPhone = null,
            string Status = null)
        {
            var statusSelectList = Enum.GetNames<OrderStatus>().ToList();

            var model = new OrderListViewModel()
            {
                OrderHeadersList = orderHeaderDB.GetAll().ToList(),
                StatusList = new SelectList(statusSelectList),

            };

            if (searchName != null)
                model.OrderHeadersList = model.OrderHeadersList.Where(x => x.FullName.ToLower()
                                                               .Contains(searchName.ToLower())).ToList();

            if(searchEmail != null)
                model.OrderHeadersList = model.OrderHeadersList.Where(x => x.Email.ToLower()
                                                               .Contains(searchEmail.ToLower())).ToList();

            if(searchPhone != null)
                model.OrderHeadersList = model.OrderHeadersList.Where(x => x.PhoneNumber.ToLower()
                                                               .Contains(searchPhone.ToLower())).ToList();

            if (Status != null)
                model.OrderHeadersList = model.OrderHeadersList.Where(x => x.OrderStatus == Status).ToList();

            return View(model);
        }

        [HttpGet]
        public IActionResult Details(int? id)
        {
            var orderHeader = orderHeaderDB.FindById(id.GetValueOrDefault());

            if (orderHeader == null)
                return NotFound();

            var includeProperties = new List<string>() { WebConstants.ProductName };
            var orderDetailsList = orderDetailsDB.GetAll(predicate: x => x.OrderHeaderId == orderHeader.Id,
                                                         includeProperties: includeProperties);

            var model = new OrderViewModel()
            {
                OrderHeader = orderHeader,
                OrderDetailsList = orderDetailsList.ToList()
            };

            return View(model); 
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult StartProcessing(OrderViewModel model)
        {
            var orderHeader = orderHeaderDB.FindById(model.OrderHeader.Id);

            if (orderHeader == null)
                return NotFound();

            orderHeader.OrderStatus = OrderStatus.InProcess.ToString();
            orderHeaderDB.Update(orderHeader);
            orderHeaderDB.Save();

            TempData[WebConstants.Success] = "Order is in process";

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ShipOrder(OrderViewModel model)
        {
            var orderHeader = orderHeaderDB.FindById(model.OrderHeader.Id);

            if (orderHeader == null)
                return NotFound();

            orderHeader.OrderStatus = OrderStatus.Shipped.ToString();
            orderHeader.ShippingDate = DateTime.Now;
            orderHeaderDB.Update(orderHeader);
            orderHeaderDB.Save();

            TempData[WebConstants.Success] = "Order shipped successfully";

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CancelOrder(OrderViewModel model)
        {
            var orderHeader = orderHeaderDB.FindById(model.OrderHeader.Id);

            if (orderHeader == null)
                return NotFound();

            orderHeader.OrderStatus = OrderStatus.Refunded.ToString();
            orderHeaderDB.Update(orderHeader);
            orderHeaderDB.Save();

            TempData[WebConstants.Success] = "Order cancelled successfully";

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult UpdateOrderDetails(OrderViewModel model)
        {
            var orderHeader = orderHeaderDB.FindById(model.OrderHeader.Id);

            if (orderHeader == null)
                return NotFound();

            orderHeader.FullName = model.OrderHeader.FullName;
            orderHeader.PhoneNumber = model.OrderHeader.PhoneNumber;
            orderHeader.StreetAddress = model.OrderHeader.StreetAddress;
            orderHeader.City = model.OrderHeader.City;
            orderHeader.State = model.OrderHeader.State;
            orderHeader.PostalCode = model.OrderHeader.PostalCode;
            orderHeader.Email = model.OrderHeader.Email;

            orderHeaderDB.Update(orderHeader);
            orderHeaderDB.Save();

            TempData[WebConstants.Success] = "Order details updated successfully";

            return RedirectToAction(nameof(Details), new { Id = orderHeader.Id});
        }
    }
}

ShopMVC/Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ShopMVC_DataAccess;
using ShopMVC_Models;
using ShopMVC_Utility;
using ShopMVC_ViewModels;

namespace ShopMVC.Controllers
{
    [Authorize(Roles = WebConstants.AdminRole)]
    public class ProductController : Controller
    {
        private readonly IProductRepository db;
        private readonly IWebHostEnvironment hostingEnvironment;
        public ProductController(IProductRepository db, IWebHostEnvironment hostingEnvironment)
        {
            this.db = db;
            this.hostingEnvironment = hostingEnvironment;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var includeProperties = new List<string>()
            {
                WebConstants.CategoryName,
                WebConstants.ApplicationTypeName
            };

            var products = db.GetAll(includeProperties: includeProperties).ToList();

            return View(products);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var categoriesSelectList = db.GetSelectList(WebConstants.CategoryName);
            var appTypesSelectList = db.GetSelectList(WebConstants.ApplicationTypeName);

            var model = new CreateProductViewModel()
            {
                CategorySelectList = categoriesSelectList,
                ApplicationTypesSelectList = appTypesSelectList,
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateProductViewModel model)
        {
            if (ModelState.IsValid)
            {
                string uniqueFileName = await FileHandler.ProcessUploadedFile(model.Image, hostingEnvironment);

                var product = new Product()
                {
                    Name = model.Name,
                    Price = model.Price,
                    Description = model.Description,
                    ShortDescription = model.ShortDescription,
                    PhotoPath = uniqueFileName,
                    CategoryId = model.CategoryId,
                    ApplicationTypeId = model.ApplicationTypeId
                };

                db.Add(product);
                db.Save();

                return RedirectToAction(nameof(Index));
            }

            var categoriesSelectList = db.GetSelectList(WebConstants.CategoryName);
            var appTypesSelectList = db.GetSelectList(WebConstants.ApplicationTypeName);

            model.CategorySelectList = categoriesSelectList;
            model.ApplicationTypesSelectList = appTypesSelectList;

            return View(model);
        }


        [HttpGet]
        public IActionResult Edit(int? id)
        {
            var product = db.FindById(id.GetValueOrDefault());

            if (product == null)
                return NotFound();

            var model = new EditProductViewModel()
            {
                Id = product.Id,
                Name = product.Name,
                Description = product.Description,
                ShortDescription = product.ShortDescription,
                Price = product.Price,
                CategoryId = product.CategoryId,
                ApplicationTypeId = product.ApplicationTypeId,
                PhotoPath = product.PhotoPath,
            };

            var categoriesSelectList = db.GetSelectList(WebConstants.CategoryName);
            var appTypesSelectList = db.GetSelectList(WebConstants.ApplicationTypeName);

            model.CategorySelectList = categoriesSelectList;
            model.ApplicationTypesSelectList = appTypesSelectList;

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditProductViewModel model)
        {
            if (ModelState.IsValid)
            {
                var product = db.FindById(model.Id);

                if (product == null)
                    return NotFound();

                product.Name = model.Name;
                product.Price = model.Price;
                product.Description = model.Description;
                product.ShortDescription = model.ShortDescription;
                product.CategoryId = model.CategoryId;
                product.ApplicationTypeId = model.ApplicationTypeId;
                product.PhotoPath = model.PhotoPath;

                if (model.Image != null) // if we uploaded a new photo
                {
                    if (model.PhotoPath != null) // if product already had a photo
                    {
                        // delete photo product has
                        var filePath = Path.Combine(hostingEnvironment.WebRootPath, WebConstants.ImagePath, model.PhotoPath);

                        if (System.IO.File.Exists(filePath))
                            System.IO.File.Delete(filePath);
                    }

                    product.PhotoPath = await FileHandler.ProcessUploadedFile(model.Image, hostingEnvironment);
                }

                db.Update(product);
                db.Save();

                return RedirectToAction(nameof(Index));
            }

            var categoriesSelectList = db.GetSelectList(WebConstants.CategoryName);
            var appTypesSelectList = db.GetSelectList(WebConstants.ApplicationTypeName);

            model.CategorySelectList = categoriesSelectList;
            model.ApplicationTypesSelectList = appTypesSelectList;

            return View(model);
        }

        [HttpGet]
        public IActionResult Delete(int? id)
        {
            var product = db.FindById(id.GetValueOrDefault());

            if (product == null)
                return NotFound();

            var model = new DeleteProductViewModel()
            {
                Name = product.Name,
                Price = product.Price,
                Description = product.Description,
                ShortDescription = product.ShortDescription,
                CategoryId = product.CategoryId,
                ApplicationTypeId = product.ApplicationTypeId,
                PhotoPath = product.PhotoPath
            };

            var categoriesSelectList = db.GetSelectList(WebConstants.CategoryName);
            var appTypesSelectList = db.GetSelectList(WebConstants.ApplicationTypeName);

            model.CategorySelectList = categoriesSelectList;
            model.ApplicationTypesSelectList = appTypesSelectList;

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(DeleteProductViewModel model)
        {
            var product = db.FindById(model.Id);

            if (product == null)
                return NotFound();

            // delete photo product has
            if (product.PhotoPath != null)
            {
                var filePath = Path.Combine(hostingEnvironment.WebRootPath, WebConstants.ImagePath, product.PhotoPath);

                if (System.IO.File.Exists(filePath))
                    System.IO.File.Delete(filePath);
            }

            db.Remove(product);
            db.Save();

            return RedirectToAction(nameof(Index));
        }
    }
}

ShopMVC/Views/Shared/_IndividualProductCard.cshtml
@model Product

@{
	var photoPath = WebConstants.ImagePath + Model.PhotoPath;
}

<div class="col-lg-4 col-md-6 pb-4 filter @Model.Category.Name.Replace(' ','_')">

	<div class="card bg-white rounded shadow-sm" style="border:1px solid #222">

		<div class="card-body px-3 pt-3 pb-1 row">
			<div class="col-7">
				<label class="float-left"> @Model.Name </label>
			</div>
			<div class="col-5 text-end">
				<label class="float-right">
					<span class="text-info h5"> @string.Format("{0:c0}", Model.Price) </span> / sqft
				</label>
			</div>
		</div>

		<img class="card-img-top img-fluid d-block mx-auto mb-3" src="@photoPath" alt="Card image cap" />

		<div class="card-body p-1 px-3 row">

			<div class="col-6">
				<span class="badge p-2 border w-100" style="background-color:lavenderblush">
					<span style="color:black"> @Model.Category.Name </span>
				</span>
			</div>

			<div class="col-6 border-0">
				<span class="badge p-2 border w-100" style="background-color:aliceblue">
					<span style="color:black"> @Model.ApplicationType.Name </span>
				</span>
			</div>

			<div class="col-12 pt-2" style="font-size:13px; text-align:justify">
				<p> @Model.ShortDescription </p>
			</div>

			<div class="col-12 p-1">
				<a asp-controller="Home" asp-action="Details" asp-route-id="@Model.Id" class="btn btn-dark form-control btn-sm p-2" style="height:40px"> View Details </a>
			</div>

		</div>
	</div>
</div>

ShopMVC/Views/Shared/_Layout.cshtml
@{
	var sessionCart = Context.Session.Get<List<ShoppingCart>>(WebConstants.SessionCart);
}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title> @ViewData["Title"] - ShopMVC </title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-lumen.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.css" integrity="sha256-He3QEBKoL/nMXlVsoM7S2C2kjFQqS5L+mgA+F8LpG+U=" crossorigin="anonymous" />
	<link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
	<link rel="stylesheet" href="~/FontAwesome/css/all.css" asp-append-version="true" />/>
	<link rel="stylesheet" href="https://cdn.syncfusion.com/ej2/20.3.56/fluent.css" />
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
			<div class="container-fluid">

				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
					<img src="~/images/tile.png" width="40%" />
				</a>

				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>

				<div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">

					@await Html.PartialAsync("_LoginPartial")

					<ul class="navbar-nav flex-grow-1">

						<li class="nav-item">
							<a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index"> Home </a>
						</li>

						@if (User.IsInRole(WebConstants.AdminRole))
						{
							<li class="nav-item dropdown">
								<a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
									Content Management
								</a>

								<div class="dropdown-menu" style="">
									<a class="dropdown-item" asp-area="" asp-controller="Category" asp-action="Index"> Category </a>
									<a class="dropdown-item" asp-area="" asp-controller="ApplicationType" asp-action="Index"> App Types </a>
									<a class="dropdown-item" asp-controller="Product" asp-action="Index"> Products </a>
									<div class="dropdown-divider"></div>
									<a class="dropdown-item" asp-area="Identity" asp-page="/Account/Register"> Create Admin User </a>
								</div>
							</li>

							<li class="nav-item dropdown">
								<a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
									Order/Inquiry Management
								</a>

								<div class="dropdown-menu" style="">
									<a class="dropdown-item" asp-area="" asp-controller="Inquiry" asp-action="Index"> Inquiry </a>
									<a class="dropdown-item" asp-area="" asp-controller="Order" asp-action="Index"> Orders </a>
								</div>
							</li>
						}

						<li>
							@if (sessionCart != null)
							{
								<a asp-controller="ShoppingCart" asp-action="Index" class="nav-link">
									<i class="fas fa-shopping-cart"></i> @sessionCart.Count
								</a>
							}
							else
							{
								<a asp-controller="ShoppingCart" asp-action="Index" class="nav-link">
									<i class="fas fa-shopping-cart"></i> (0)
								</a>
							}
						</li>
					</ul>
				</div>

			</div>
		</nav>
	</header>

	<div class="container">
		<main role="main" class="pb-3">
			@await Html.PartialAsync("_Notifications")
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer bg-dark">
		<div class="container text-white-50">
			&copy; 2022 - ShopMVC
		</div>
	</footer>

	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	<script src="https://cdn.syncfusion.com/ej2/20.3.56/dist/ej2.min.js"></script>

	@await RenderSectionAsync("Scripts", required: false)

	<ejs-scripts></ejs-scripts>

</body>
</html>

ShopMVC/Views/Shared/_Notifications.cshtml
@if (TempData[WebConstants.Success] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData[WebConstants.Success]');
    </script>
}
@if (TempData[WebConstants.Error] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData[WebConstants.Error]');
    </script>
}