ShopMVC/Controllers/ApplicationTypeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ShopMVC_DataAccess;
using ShopMVC_Models;
using ShopMVC_Utility;

namespace ShopMVC.Controllers
{
    [Authorize(Roles = WebConstants.AdminRole)]
    public class ApplicationTypeController : Controller
    {
        private readonly IApplicationTypeRepository db;
        public ApplicationTypeController(IApplicationTypeRepository db)
        {
            this.db = db;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var appTypes = db.GetAll().ToList();
            return View(appTypes);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ApplicationType appType)
        {
            if (ModelState.IsValid)
            {
                db.Add(appType);
                db.Save();

                return RedirectToAction(nameof(Index));
            }

            return View(appType);
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            var appType = db.FindById(id.GetValueOrDefault());

            if (appType == null)
                return NotFound();

            return View(appType);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(ApplicationType type)
        {
            if (ModelState.IsValid)
            {
                db.Update(type);
                db.Save();

                return RedirectToAction(nameof(Index));
            }

            return View(type);
        }

        [HttpGet]
        public IActionResult Delete(int? id)
        {
            var appType = db.FindById(id.GetValueOrDefault());

            if (appType == null)
                return NotFound();

            return View(appType);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmation(int? id)
        {
            var appType = db.FindById(id.GetValueOrDefault());

            if (appType == null)
                return NotFound();

            db.Remove(appType);
            db.Save();

            return RedirectToAction(nameof(Index));
        }
    }
}

ShopMVC/Views/ApplicationType/Create.cshtml
@model ApplicationType

@{
	ViewData["Title"] = "New Application Type";
}


<h2 class="text-primary mt-4"> Create Application Type </h2>
<hr />

<form asp-controller="ApplicationType" asp-action="Create" method="post">

	<div asp-validation-summary="All" class="text-danger"></div>

	<div class="mb-3">
		<label asp-for="Name" class="form-label"> Name </label>
		<input asp-for="Name" class="form-control col-4">
		<div class="form-text"> Enter app type name </div>
		<span asp-validation-for="Name" class="text-danger"></span>
	</div>

	<button type="submit" class="btn btn-success"> Create </button>
	<a asp-controller="ApplicationType" asp-action="Index" class="btn btn-danger">
		<i class="fa fa-sign-out-alt"></i> Back
	</a>

</form>

@section Scripts{
	@await Html.PartialAsync("_ValidationScriptsPartial");
    }

ShopMVC/Views/ApplicationType/Delete.cshtml
@model ApplicationType

@{
	ViewData["Title"] = "Delete ApplicationType";
}

<h2 class="text-primary mt-4"> Delete ApplicationType </h2>
<hr />

<form asp-controller="ApplicationType" asp-action="DeleteConfirmation" method="post">

	<div asp-validation-summary="All" class="text-danger"></div>

	<input type="hidden" asp-for="Id" />

	<div class="mb-3">
		<label asp-for="Name" class="form-label"> Name </label>
		<input asp-for="Name" disabled class="form-control col-4">
		<span asp-validation-for="Name" class="text-danger"></span>
	</div>

	<button type="submit" class="btn btn-success"> Delete </button>
	<a asp-controller="ApplicationType" asp-action="Index" class="btn btn-danger">
		<i class="fa fa-sign-out-alt"></i> Back
	</a>

</form>

ShopMVC/Views/ApplicationType/Edit.cshtml
@model ApplicationType

@{
	ViewData["Title"] = "Edit Application Type";
}

<h2 class="text-primary mt-4"> Edit Application Type </h2>
<hr />

<form asp-controller="ApplicationType" asp-action="Edit" method="post">

	<div asp-validation-summary="All" class="text-danger"></div>

	<input type="hidden" asp-for="Id" />

	<div class="mb-3">
		<label asp-for="Name" class="form-label"> Name </label>
		<input asp-for="Name" class="form-control col-4">
		<div class="form-text"> Enter category name </div>
		<span asp-validation-for="Name" class="text-danger"></span>
	</div>

	<button type="submit" class="btn btn-success"> Update </button>
	<a asp-controller="ApplicationType" asp-action="Index" class="btn btn-danger">
		<i class="fa fa-sign-out-alt"></i> Back
	</a>

</form>

@section Scripts{
	@await Html.PartialAsync("_ValidationScriptsPartial");
    }

ShopMVC/Views/ApplicationType/Index.cshtml
@model IEnumerable<ApplicationType>

@{
	ViewData["Title"] = "Index";
}

<h1> INDEX </h1>

<div class="container p-3">
	<div class="row pt-4">

		<div class="col-6">
			<h2 class="text-primary"> Application Types List </h2>
		</div>

		<div class="col-6 text-end">
			<a asp-controller="ApplicationType" asp-action="Create" class="btn btn-primary"> 
				<i class="fas fa-plus"></i> New Application Type
			</a>
		</div>

	</div>

	<br />

	@if (Model.Count() > 0)
	{
		<table class="table table-bordered table-striped" style="width:100%">

			<thead>
				<tr>
					<th> Application Type Name </th>
					<th></th>
				</tr>
			</thead>

			<tbody>
				@foreach (var type in Model)
				{
					<tr>
						<td style="width:50%"> @type.Name </td>
						<td class="text-center">
							<div>
								<a asp-controller="ApplicationType" asp-action="Edit" asp-route-id="@type.Id" class="btn btn-primary mx-1">
									<i class="fas fa-edit"></i>
								</a>
								<a asp-controller="ApplicationType" asp-action="Delete" asp-route-id="@type.Id" class="btn btn-danger mx-1">
									<i class="fas fa-trash-alt"></i>
								</a>
							</div>
						</td>
					</tr>
				}
			</tbody>

		</table>
	}
	else
	{
		<p> No application types exist. </p>
	}
</div>